### ISSUE TITLE
github pages のページを追加する

### ISSUE THREAD

**Issue by dariaGlint** [dariaGlint/dariarchive.github.io#3]

**Comment by dariaGlint** [comment]
- [x]  [ここ](https://jekyllrb-ja.github.io/docs/installation/windows/)を見ながらRubyとJekyllのインストール

**Comment by dariaGlint** [comment]
上だけでは解決できなかったので、[ここ](https://qiita.com/ichi-ken/items/6dda6f1e2ad66858fcd7)を見ながら環境構築

# ハマった所
- jekyll new --skip-bundle .　は空のフォルダにしかできない

- bundle exec jekyll serve を呼んだらエラーが出た


```Bash
<internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- webrick (LoadError)
        from <internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from C:/Users/自分のPCでログインしてるUserName/.local/share/gem/ruby/3.2.0/gems/jekyll-3.9.3/lib/jekyll/commands/serve/servlet.rb:3:in `<top (required)>'
        from C:/Users/自分のPCでログインしてるUserName/.local/share/gem/ruby/3.2.0/gems/jekyll-3.9.3/lib/jekyll/commands/serve.rb:184:in `require_relative'
        from C:/Users/自分のPCでログインしてるUserName/.local/share/gem/ruby/3.2.0/gems/jekyll-3.9.3/lib/jekyll/commands/serve.rb:184:in `setup'
        from C:/Users/自分のPCでログインしてるUserName/.local/share/gem/ruby/3.2.0/gems/jekyll-3.9.3/lib/jekyll/commands/serve.rb:102:in `process'
        from C:/Users/自分のPCでログインしてるUserName/.local/share/gem/ruby/3.2.0/gems/jekyll-3.9.3/lib/jekyll/commands/serve.rb:93:in `block in start'
        from C:/Users/自分のPCでログインしてるUserName/.local/share/gem/ruby/3.2.0/gems/jekyll-3.9.3/lib/jekyll/commands/serve.rb:93:in `each'
        from C:/Users/自分のPCでログインしてるUserName/.local/share/gem/ruby/3.2.0/gems/jekyll-3.9.3/lib/jekyll/commands/serve.rb:93:in `start'
        from C:/Users/自分のPCでログインしてるUserName/.local/share/gem/ruby/3.2.0/gems/jekyll-3.9.3/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
        from C:/Users/自分のPCでログインしてるUserName/.local/share/gem/ruby/3.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from C:/Users/自分のPCでログインしてるUserName/.local/share/gem/ruby/3.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from C:/Users/自分のPCでログインしてるUserName/.local/share/gem/ruby/3.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from C:/Users/自分のPCでログインしてるUserName/.local/share/gem/ruby/3.2.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from C:/Users/自分のPCでログインしてるUserName/.local/share/gem/ruby/3.2.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from C:/Users/自分のPCでログインしてるUserName/.local/share/gem/ruby/3.2.0/gems/jekyll-3.9.3/exe/jekyll:15:in `<top (required)>'
        from C:/Users/自分のPCでログインしてるUserName/AppData/Local/Microsoft/WindowsApps/jekyll:25:in `load'
        from C:/Users/自分のPCでログインしてるUserName/AppData/Local/Microsoft/WindowsApps/jekyll:25:in `<main>'
```
エラー内容でググったら[こちらのサイト](https://talk.jekyllrb.com/t/load-error-cannot-load-such-file-webrick/5417)の
```bash
bundle add webrick
```
をbashに入力してEnter押したら解決した

**Comment by dariaGlint** [comment]
色々あった結果、mkDocsにすることにしました。

理由は
- markdownファイルにmetaデータを入れるのがもしZennとかに移す際にデータを削除する手間があると考えたらあまり得策ではないと思ったから
- markdownだけで完結するので管理が楽
- サイトのデザインのテーマがたくさんあって、ダークモードとかも簡単に実装出来たから
- 一日やってこれで良いなと感じたため
